const DEFAULT_SESSION_SECRET = 'y9q*uMGmx3Aw'
export const SESSION_SECRET = process.env.SESSION_SECRET || DEFAULT_SESSION_SECRET

export const MAX_MESSAGE_LENGTH = 256
export const MAX_USERNAME_LENGTH = 20